model: Resnet18
client_model: Resnet18

dataset_path: datasets/cifar100
dataset: cifar100
nclass: 100
test_dataset: cifar100
test_dataset_path: datasets/cifar100

standardize: True
augment: True

pin_memory: True
n_workers: 4
SEED: 42
batch_size: 32
gpu: 0
server_gpu: 0

adv: True
epsilon: 0.5
inner_lr: 0.01
inner_iter: 1

iid: False
beta: 0.6
alpha: 0.01
params_avg: 0.001

n_clients: 30
sample_clients: 0.3

lr: 0.001
    
total_iterations: 100
client_iterations: 5
img_size:
    - 32
    - 32
    
eval_mode: True
individual: False

opt: SGD
momentum: 0.9

# server_model: /DATA/sharma59/Know_distil/datafreekd/saved_models/resnet18_fed_avg_real_v1.pt

return_logs: False
pid: 30011